# Change these first
owner: weblate-status-bot
repo: status
user-agent: weblate-status-bot

# Add your sites here
sites:
  - name: Hosted Weblate
    url: https://hosted.weblate.org
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Weblate Care
    url: https://care.weblate.org
  - name: Weblate Documentation
    url: https://docs.weblate.org
  - name: Weblate website
    url: https://weblate.org/en/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Weblate CDN
    url: https://weblate-cdn.com/a5ba5dc29f39498aa734528a54b50d0a/weblate.js
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Weblate Cloud Backup Service
    check: "tcp-ping"
    url: backups.weblate.cloud
    port: 23
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Fedora Weblate
    url: https://translate.fedoraproject.org/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Kodi Weblate
    url: https://kodi.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Dyson Weblate
    url: https://dyson.weblate.org/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: EURid Weblate
    url: https://weblate.eurid.eu/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: EURid Weblate (staging)
    url: https://weblate-test.eurid.eu/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Solocoo Weblate
    url: https://translate.solocoo.tv/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Lime Weblate
    url: https://translate.lime.tech/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Mattermost Weblate
    url: https://translate.mattermost.com/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Bon Weblate
    url: https://bon.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: UL Weblate
    url: https://ul.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Medvice Weblate
    url: https://medvice.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Sourceability Weblate
    url: https://sourceability.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Vernier Weblate
    url: https://vernier.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Profil Klett Weblate
    url: https://profil-klett.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Preventis Weblate
    url: https://preventis.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: SNOMED Weblate
    url: https://translate.snomedtools.org/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Shopop Weblate
    url: https://weblate.shopopop.com/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Shayp Weblate
    url: https://weblate.shayp.io/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Oxfam Weblate
    url: https://oxfam.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Universal Music Weblate
    url: https://umusic.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Doka Weblate
    url: https://translation.umdaschgroup.com
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Manor Weblate
    url: https://manor.weblate.cloud
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: MetaBrainz Weblate
    url: https://translations.metabrainz.org/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: DGUV Weblate
    url: https://weblate.dguv.de/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Pascom Weblate
    url: https://translate.pascom.net/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Artefactual's Weblate
    url: https://translations.artefactual.com/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: LS Weblate
    url: https://tmhe.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Salling Weblate
    url: https://salling.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Oculavis Weblate
    url: https://weblate.oculavis.de/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: GetMomo Weblate
    url: https://weblate.getmomo.net/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Teamhero Weblate
    url: https://wl.teamhero.de/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: webit Weblate
    url: https://webit.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Schiller Weblate
    url: https://translate.schiller.fr/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Stem Weblate
    url: https://weblate.stem.com/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Spaziodati Weblate
    url: https://spaziodati.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Papirfly Weblate
    url: https://papirfly.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Viking Weblate
    url: https://viking.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png
  - name: Syncron Weblate
    url: https://syncron.weblate.cloud/
    icon: https://s.weblate.org/cdn/logo-32.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.weblate.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /status
  logoUrl: https://s.weblate.org/cdn/Logo-Darktext.png
  name: Weblate Status
  introTitle: Weblate Status Dashboard
  introMessage: You can find more information about Weblate on [weblate.org](https://weblate.org/) or you check our [hosting plans](https://weblate.org/hosting/).
  favicon: https://s.weblate.org/cdn/logo-128.png
  faviconSvg: https://s.weblate.org/cdn/weblate.svg
  links:
    - rel: stylesheet
      href: https://s.weblate.org/cdn/font-source/source-sans-pro.css
  customBodyHtml: |
    <!-- Matomo -->
    <script type="text/javascript">
      var _paq = window._paq = window._paq || [];
      /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
      _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
        var u="https://stats.cihar.com/";
        _paq.push(['setTrackerUrl', u+'matomo.php']);
        _paq.push(['setSiteId', '27']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
      })();
    </script>
    <noscript><p><img src="https://stats.cihar.com/matomo.php?idsite=27&amp;rec=1" style="border:0;" alt="" /></p></noscript>
    <!-- End Matomo Code -->
  css: |
    body {
      font-family: 'Source Sans Pro', Arial, sans-serif;
      font-weight: 400;
      font-size: 18px;
    }
    a.svelte-a08hsz {
      font-weight: 600;
      font-size: 18px;
      line-height: 23px;
    }
    h1 {
      font-size: 40px;
      font-weight: bold;
      letter-spacing: -1px;
    }
    h2 {
      font-size: 26px;
      font-weight: 400;
      letter-spacing: -0.5px;
    }
    h4 {
      font-size: 20px;
      font-weight: 700;
      letter-spacing: -0.5px;
    }
    .logo.svelte-a08hsz div {
      display: none;
    }
    .logo.svelte-a08hsz img.svelte-a08hsz {
      height: 100px;
    }
  navbar:
    - title: Status
      href: /
    - title: Support
      href: https://weblate.org/support/
    - title: GitHub
      href: https://github.com/WeblateOrg

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
