# Change these first
owner: nijel # Your GitHub username
repo: upptime-test # Your GitHub repository name

# Add your sites here
sites:
  - name: Hosted Weblate
    url: https://hosted.weblate.org
  - name: Weblate Care
    url: https://care.weblate.org
  - name: Weblate Documentation
    url: https://docs.weblate.org
  - name: Weblate website
    url: https://weblate.org/en/
  - name: Weblate CDN
    url: https://weblate-cdn.com/a5ba5dc29f39498aa734528a54b50d0a/weblate.js
  - name: Fedora Weblate
    url: https://translate.fedoraproject.org/
  - name: Rocky Linux Weblate
    url: https://translate.rockylinux.org/
  - name: Kodi Weblate
    url: https://kodi.weblate.cloud/
  - name: Dyson Weblate
    url: https://dyson.weblate.org/
  - name: EURid Weblate
    url: https://weblate.eurid.eu/
  - name: EURid Weblate (staging)
    url: https://weblate-test.eurid.eu/
  - name: Solocoo Weblate
    url: https://translate.solocoo.tv/
  - name: Lime Weblate
    url: https://translate.lime.tech/
  - name: Mattermost Weblate
    url: https://translate.mattermost.com/
  - name: Bon Weblate
    url: https://bon.weblate.cloud/
  - name: UL Weblate
    url: https://ul.weblate.cloud/
  - name: Medvice Weblate
    url: https://medvice.weblate.cloud/
  - name: Sourceability Weblate
    url: https://sourceability.weblate.cloud/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime-test
  logoUrl: https://s.weblate.org/cdn/weblate.svg
  name: Weblate Status
  introTitle: Weblate Status Dashboard
  introMessage: You can find more information about Weblate on [weblate.org](https://weblate.org/) or you check our [hosting plans](https://weblate.org/hosting/).
  favicon: https://s.weblate.org/cdn/logo-128.png
  faviconSvg: https://s.weblate.org/cdn/weblate.svg
  navbar:
    - title: Status
      href: /upptime-test/
    - title: Support
      href: https://weblate.org/support/
    - title: GitHub
      href: https://github.com/WeblateOrg

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
