name: Gotify issue
on:
  issues:
    types: [opened, closed]

jobs:
  issue-commented:
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: |
          curl "https://gotify.weblate.org/message?token=${{ secrets.GOTIFY_TOKEN }}" --data "title=${{ github.event.issue.title }} ${{ github.event.action }}" --data "message=${{ github.event.issue.body }}"
